#!/usr/bin/env bash
# Transfers a file from our client to a server using 'scp' (Secure Copy).
# Accepts 4 parameters and Strict host key checking is disabled.

if [ $# -lt 3 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi
