#!/usr/bin/env bash
# Set ups web-02 server to be identical to web-01 server.
# Adds a custom Nginx response header on web-02 and web-01 servers, to be
# able to track which web server is answering our HTTP requests:
# - The name of the custom HTTP header: X-Served-By.
# - The value of the HTTP header: hostname of the server Nginx is running on.

sudo apt update
sudo apt install nginx -y

sudo ufw allow 'Nginx HTTP'

sudo chmod -R 755 /var/www

echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

sudo sed -i '/listen 80 default_server/a \    root /var/www/html;' /etc/nginx/sites-available/default

sudo sed -i "/listen 80 default_server/a        location \/redirect_me {\n      return 301 https://www.behance.net/Aziz-Belkharmoudi/;\n}" /etc/nginx/sites-available/default

sudo sed -i "/listen 80 default_server/a error_page 404 /404.html;" /etc/nginx/sites-available/default

sudo sed -i "/listen 80 default_server/a add_header X-Served-By \$hostname;" /etc/nginx/sites-available/default

sudo service nginx restart
