#!/usr/bin/env bash
# Set ups HAproxy on lb-01 server.
# Sends traffic to web-02 and web-01 servers.
# Distribute requests using a roundrobin algorithm.

sudo apt update
# Enable a dedicated PPA package for HAProxy:
sudo apt-get -y install --no-install-recommends software-properties-common
# Adds the dedicated PPA repository
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
# Get the latest release of HAProxy 2.0 from the above PPA repository:
sudo apt-get install -y haproxy

LOAD_BALANCER_SETUP="
backend binarydesign.tech-backend
        balance roundrobin
        server 377432-web-01 3.84.161.155:80 check
        server 377432-web-02 100.25.23.133:80 check

frontend binarydesign.tech-frontend
        bind *:80
        mode http
        default_backend binarydesign.tech-backend
"

echo "ENABLED=1" >> /etc/default/haproxy
echo "$LOAD_BALANCER_SETUP" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
