#!/usr/bin/env bash
# Set ups HAproxy on lb-01 server.
# Sends traffic to web-02 and web-01 servers.
# Distribute requests using a roundrobin algorithm.

sudo apt update
# Enable a dedicated PPA package for HAProxy:
sudo apt-get -y install --no-install-recommends software-properties-common
# Adds the dedicated PPA repository
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
# Get the latest release of HAProxy 2.0 from the above PPA repository:
sudo apt-get install haproxy=2.0.\* -y

DOMAIN_NAME="binarydesign.tech"
HAPROXY_INIT_FILE="/etc/default/haproxy"
HAPROXY_CONFIG_FILE="/etc/haproxy/haproxy.cfg"

LOAD_BALANCER_SETUP="
backend $DOMAIN_NAME-backend
	balance roundrobin
	server 377432-web-01 3.84.161.155:80 check
	server 377432-web-02 100.25.23.133:80 check

frontend $DOMAIN_NAME-frontend
	bind *:80
	mode http
        default_backend $DOMAIN_NAME-backend
"

echo -e "ENABLED=1\n" >> "$HAPROXY_INIT_FILE"
echo "$LOAD_BALANCER_SETUP" >> "$HAPROXY_CONFIG_FILE"

sudo service haproxy restart
