#!/usr/bin/env bash
# This is a Bash script that pings an IP address passed as an argument.
# Accepts a string as an argument.
IP_INPUT=$1
# Displays the script Usage.
if [ $# -ne 1 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"; exit 1
fi
# Ping the IP 5 times.
ping -c 5 "$IP_INPUT"
