#!/usr/bin/env bash
# This is a Bash script pings an IP address passed as an argument.
# Accepts a string as an argument.
# Ping the IP 5 times.

IP_INPUT=$1

if [ $# -ne 1 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"; exit 1
fi

ping -c 5 "$IP_INPUT"
