#!/usr/bin/env bash
# Fix what’s keeping my Ubuntu container’s Nginx installation from listening on port 80.

# Checks nginx installation.
sudo apt update
sudo apt install nginx -y

# Checks if nginx is already configured to listen on port 80. If not, modifie the nginx configuration to listen on port 80.
sudo ufw allow 'Nginx HTTP'

# Restart nginx to apply the change
sudo service nginx restart
