#!/usr/bin/env bash
# Fix what’s keeping my Ubuntu container’s Nginx installation from listening on port 80.
# Disable the default Nginx server block configuration enable it again, and then restart Nginx

# Delete the symbolic link located at Nginx server block configuration
rm /etc/nginx/sites-enabled/default
# Create a new ymbolic link
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restart nginx to apply the change
sudo service nginx restart
