#!/usr/bin/env bash
# Fix what’s keeping my Ubuntu container’s Nginx installation from listening on port 80.
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
sudo service nginx restart
sudo pkill nginx
