#!/usr/bin/env bash
# Fix what’s keeping my Ubuntu container’s Nginx installation from listening on port 80.
ln -s -f /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo pkill nginx
