#!/usr/bin/env bash
# This is a Bash script that displays Creates the file /var/run/myscript.pid containing its PID.
sigint_handler(){
	echo "Y U no love me?!"
}
sigterm_handler(){
	echo "I hate the kill command"
	rm /var/run/myscript.pid
	exit
}

trap 'sigint_handler' SIGINT
trap 'sigterm_handler' SIGTERM SIGQUIT

echo $$ >> /var/run/myscript.pid

while true; do
	echo "To infinity and beyond"
	sleep 2
done
