#!/usr/bin/env bash
# This is a Bash script that manages manage_my_process.
start(){
	./manage_my_process &
	sleep 2
	echo "manage_my_process started"
}
stop(){
	pid=$(cat /var/run/my_process.pid)
	kill "$pid"
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
}
restart(){
	stop
	sleep 1
	start
	echo "manage_my_process restarted"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		exit 1
esac

exit 0
