#!/usr/bin/env bash
# This is a Bash script that manages manage_my_process.
. ./manage_my_process
start(){
	daemon &
	PID=$!
	echo $PID > /var/run/my_process.pid
	echo "manage_my_process started"
}
stop(){
	kill "$(cat /var/run/my_process.pid)"
	rm -f /var/run/my_process.pid
	echo "manage_my_process stopped"
}
restart(){
	stop
	start
	echo "manage_my_process restarted"
}

case "$1" in
	start) start ;;
	stop) stop ;;
	restart) restart ;;
	*) echo "Usage: manage_my_process {start|stop|restart}"; exit 1
esac

exit 0
