#!/usr/bin/env bash
# This a Bash script that displays numbers from 1 to 100 and performs FizzBuzz.
count=100
for ((i=1; i<=count; i++)); do
	if (( i % 3 == 0 && i % 5 == 0)); then
		echo "FizzBuzz"
	elif (( i % 3 == 0 )); then
		echo "Fizz"
	elif (( i % 5 == 0 )); then
		echo "Buzz"
	else
		echo "$i"
	fi
done
