#!/usr/bin/env bash
# This a Bash script that groups visitors by IP and HTTP status code, and displays this data.
logfile="apache-access.log"
awk '{print $1 " " $9}' "$logfile" | sort | uniq -c | sort -rn
