#!/usr/bin/env bash
# This a Bash script that displays the time for 12 hours and 59 minutes.
h=0
while [ $h -le 12 ]; do
	if [ $h -le 12 ]; then
		echo "Hour: $h"
	fi
	m=1
	while [ $m -le 59 ]; do
		echo "$m"
		m=$((m + 1))
	done
	h=$((h + 1))
done
