#!/usr/bin/env bash
# This a Bash script that displays The content of the current directory.
for f in *; do
	if [ ! -d "$f" ] && [[ ! "$f" =~ ^\. ]]; then
		newname="${f#*-}"
		echo "$newname"
	fi
done
