#!/usr/bin/env bash
# Reloads Gunicorn in a graceful way
# By sending the HUP (Hang Up) signal to the Gunicorn master process
#shellcheck disable=SC2009
ps auxf | grep gunicorn | awk '{ print $2 }' | xargs kill -HUP
